---
title: "08 - Probability distribution"
author: "Chun Yu, Ko"
date: "2022-10-28"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 3
    number_sections: true
---

[Home page](https://seimwiwa.github.io/scu_master_degree_program_data_science_statistical_analysis/)

# Key point

```{r, echo=F, warning=F, message=F}
library(dplyr)
library(kableExtra)
library(ggplot2)
library(ggthemes)
library(colorspace)
library(ggfortify)
```

## Normal distribution

### PDF 機率密度函數

```{r, echo=F, warning=F, message=F}

ggdistribution(dnorm, seq(-3, 3, 0.1), mean = 0, sd = 1)+
  labs(title = "PDF", x = "Times, as positive", y = "Prob.")+
  theme_fivethirtyeight()+
  theme(legend.position = "none",
        axis.title = element_text())

```

### CDF 累積機分佈率函數


```{r, echo=F, warning=F, message=F}

ggdistribution(pnorm, seq(-3, 3, 0.1), mean = 0, sd = 1)+
  labs(title = "CDF", x = "Times, as positive", y = "Prob.")+
  theme_fivethirtyeight()+
  theme(legend.position = "none",
        axis.title = element_text())

```


## Summary table for distribution

|Distribution|Mean|SD|
|------------|----|--|
|binomial|$np$|$\sqrt{npq}$|
|poisson|$\lambda$|$\sqrt{\lambda}$|
|normal|$\mu$|$\sigma$|
|standard normal|$0$|$1$|

standard normal 為定義一新的數 z ，$z = \frac {x-\mu}{\sigma}$

