---
title: "08 - Hypothesis testing"
author: "Chun Yu, Ko"
date: "2022-11-18"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 3
    number_sections: true
---

[Home page](https://seimwiwa.github.io/scu_master_degree_program_data_science_statistical_analysis/)

# Key point

```{r, echo=F, warning=F, message=F}
library(dplyr)
library(data.table)
library(kableExtra)
library(ggplot2)
library(ggthemes)
library(colorspace)
```

# Proportion

假設有一群樣本 n 來自 binominal distrebution

則發生事件 x 的比例（百分比），可以記錄為：

$ p = \frac{x}{n} = \frac{number of success}{sample size}$

$ z_{cal} = \frac{p - \pi_0}{\sigma_p} = $

# 檢定統計量

## Z 檢定 Known variance

## 兩個獨立樣本 T 檢定 Two sample T test Unknown variancebut assume equal

變異數同質

### On-class practice

#### 樣本分佈

```{r, echo=F, warning=F, message=F}

dat = "20221118_Hypothesis_testing_t_test.csv"%>%
  fread

dat%>%
  mutate(Group = Group%>%factor())%>%
  ggplot(aes(x = Price, fill = Group, color = Group))+
  geom_density(alpha = .3)+
  scale_x_continuous(labels = scales::comma_format(prefix = "$"))+
  scale_y_continuous(labels = scales::percent_format())+
  scale_color_discrete_diverging("Blue Red")+
  scale_fill_discrete_diverging("Blue Red")+
  theme_fivethirtyeight()

```

```{r, echo=F, warning=F, message=F}

dat%>%
  select(Group, Price)%>%
  group_by(Group)%>%
  summarise(sample = n(),
            mean = Price%>%mean,
            sd = Price%>%sd,
            q1 = Price %>% quantile(., probs = .25),
            q2 = Price %>% quantile(., probs = .50),
            q3 = Price %>% quantile(., probs = .75),)%>%
  mutate_at(.vars =c(3:7), ~scales::comma(.,accuracy = .01))%>%
  kable(col.names = c("組別", "樣本數", "平均值", "標準差", "25%", "50%", "75%"), align = "r")%>%
  kable_styling(full = F, c("hover", "striped"))
  
dat_price_1 = dat%>%filter(Group=="1")%>%pull(Price)

dat_price_2 = dat%>%filter(Group=="2")%>%pull(Price)

```

#### 獨立樣本 t 檢定，雙尾，變異數不相等

```{r, echo=F, warning=F, message=F}
t.test(dat_price_1, dat_price_2, alternative = "two.side", var.equal = FALSE)
```

#### 獨立樣本 t 檢定，雙尾，變異數相等

```{r, echo=F, warning=F, message=F}
t.test(dat_price_1, dat_price_2, alternative = "two.side", var.equal = TRUE)
```

#### F 檢定測試變異數是否相等

```{r, echo=F, warning=F, message=F}
var.test(dat_price_1, dat_price_2)
```





## Unknown variancebut assume not equal

